services:
  backend:
    build:
      context: ./backend/legal-app
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-3030}
      DB_HOST: udocument-do-user-24626001-0.d.db.ondigitalocean.com
      DB_PORT: 25060
      DB_USER: doadmin
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: udocument
      DB_SSL: "true"
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
    expose:
      - "${BACKEND_PORT:-3030}"
    shm_size: "1gb"
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend/legalapp-front
    container_name: frontend
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT:-3000}
      NEXT_PUBLIC_API_DOMAIN: ${NEXT_PUBLIC_API_DOMAIN:-/api}
    expose:
      - "${FRONTEND_PORT:-3000}"
    networks:
      - app_net

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx-certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    networks:
      - app_net

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - nginx-certbot-www:/var/www/certbot
    command: sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet && echo "Certs renewed"; sleep 12h; done'
    networks:
      - app_net

volumes:
  certbot-etc:
  nginx-certbot-www:

networks:
  app_net:
    driver: bridge
